# Generated by Django 5.0.6 on 2025-09-12 16:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='gps_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='Max speed in m/s', null=True)),
                ('avg_speed', models.FloatField(blank=True, help_text='Average speed in m/s', null=True)),
                ('min_latitude', models.FloatField(blank=True, null=True)),
                ('max_latitude', models.FloatField(blank=True, null=True)),
                ('min_longitude', models.FloatField(blank=True, null=True)),
                ('max_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.FloatField(help_text='Time in seconds from start')),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('original_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='gps_app.gpstrack')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['track', 'timestamp'], name='gps_app_gps_track_i_f19a80_idx')],
            },
        ),
    ]
